_wandb:
    value:
        cli_version: 0.24.2
        e:
            lf8yb5dp8c1dmfs6wjlthgi5kh0utap4:
                codePath: c:\Users\master4\Desktop\seminarski-rad-hepatitis-c-prediction-dataset\hepatitis_wandb.ipynb
                codePathLocal: hepatitis_wandb.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "475268489216"
                        used: "426889605120"
                email: tekiiicaaa99@gmail.com
                executable: c:\Users\master4\anaconda3\envs\tracking_env\python.exe
                git:
                    commit: 1ca158c0f09417297666452e187ac46ac1fbe6e7
                    remote: https://github.com/teodorajeremic/seminarski-rad-hepatitis-c-prediction-dataset.git
                gpu: NVIDIA GeForce GTX 1660
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1408
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce GTX 1660
                      uuid: GPU-051886c9-beef-b2fb-def0-12b7f032e0c1
                host: PC-01
                memory:
                    total: "17125666816"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\master4\Desktop\seminarski-rad-hepatitis-c-prediction-dataset\hepatitis_wandb.ipynb
                python: CPython 3.8.20
                root: c:\Users\master4\Desktop\seminarski-rad-hepatitis-c-prediction-dataset
                startedAt: "2026-02-23T10:12:34.372886Z"
                writerId: lf8yb5dp8c1dmfs6wjlthgi5kh0utap4
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.8.20
            "5": 0.24.2
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.24.2
            "13": windows-amd64
features:
    value:
        - Age
        - Sex
        - ALB
        - ALP
        - ALT
        - AST
        - BIL
        - CHE
        - CHOL
        - CREA
        - GGT
        - PROT
max_depth:
    value: 10
model:
    value: RandomForest
n_estimators:
    value: 50
test_size:
    value: 0.2
